FROM maven:3.9-eclipse-temurin-21-alpine AS builder

WORKDIR /build
COPY ./discovery-service/pom.xml ./
COPY ./discovery-service/src ./src
RUN mvn clean install -DskipTests

FROM eclipse-temurin:21-jdk-alpine

RUN apk add --no-cache curl

WORKDIR /app
COPY --from=builder /build/target/discovery-service-1.0.0.jar app.jar

RUN mkdir -p /app/logs

EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]